name: smart_pill_organizer_app
description: "Smart Pill Organizer - IoT Application for medication management"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.1
  firebase_messaging: ^15.2.1

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Utils
  intl: ^0.20.2
  crypto: ^3.0.6
  collection: ^1.19.1
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^19.0.0

  # Charts
  fl_chart: ^0.70.2

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
