name: smart_pill_organizer_app
description: "Smart Pill Organizer - IoT Application for medication management"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  firebase_messaging: ^15.1.6

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Utils
  intl: ^0.19.0
  crypto: ^3.0.6
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^18.0.1

  # Charts
  fl_chart: ^0.69.2

  # UI
  google_fonts: ^6.2.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
